AyanoKotek/Vroomie

app/assets/stylesheets/pages/_home.scss, app/models/user.rb, app/views/pages/home.html.erb, config/routes.rb
i adde an index page with a navbar
=> index page

db/seeds.rb
Added cars instances in seeds.rb
=> seeded users and cars

Gemfile, Gemfile.lock, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_show_car.scss, app/controllers/cars_controller.rb, app/models/car.rb, app/views/cars/new.html.erb, app/views/cars/show.html.erb, config/environments/development.rb, config/storage.yml, db/migrate/20230314154612_create_active_storage_tables.active_storage.rb, db/schema.rb
Added ability to add photo to instance of car
=> Fixphotoupload

app/controllers/pages_controller.rb, app/views/layouts/application.html.erb
1. Set sign in/out link on nav bar. 
2. Added skip_before_action on home action in Pages Controller
=> Sign in/out link & skip_before_action on homepage

app/views/layouts/application.html.erb, db/seeds.rb
Edited the user instance info to make them easier to remember.
=> Made users info simpler

db/seeds.rb
added more user data and created booking data
=> added more seed data

app/views/cars/show.html.erb
Added buttons of the same size
=> changed the button to be larger

db/seeds.rb
Commented out the cars and bookings seeds so that we can show creating them in demo
=> commented out the cars and bookings seeds

app/controllers/cars_controller.rb, app/models/car.rb, app/views/cars/new.html.erb, app/views/cars/show.html.erb
Added ability to add multiple images
=> added multiple photo ability

app/views/bookings/index.html.erb
In bookings index page, fixed the method: :delete
=> delete feature link fixed

app/controllers/cars_controller.rb, app/views/cars/edit.html.erb, app/views/cars/show.html.erb, config/routes.rb
added edit and update to controller
added edit view
added editable form with old info on car/edit
=> added ability to edit listing

app/views/cars/new.html.erb
Added a label to simple_form to remind that it must be a minimum of three photos
=> Added label on photo upload

app/views/cars/index.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
made index page for car to show the map
fixed the path to some routes
=> Fixed routes 

app/assets/stylesheets/components/_carousel.scss, app/assets/stylesheets/components/_index.scss
Added _carousel.scss file in components
in file changed setting of carousel to stay fixed and fit object to carousel size
=> carousel is in a fixed position when scrolling

app/views/cars/edit.html.erb, app/views/cars/new.html.erb
The edit and new should now have the ability to write in the address of the car
=> added address to edit and new page for car creation

app/models/car.rb
Added validations in the Car model
added custom message on new creation of car
=> added validation and custom message on error

app/assets/stylesheets/pages/_carousel.scss
Added to carousel.scss to fix it tho the middle of the page
=> fixed the carousel to the middle

app/views/bookings/new.html.erb, db/migrate/20230316141607_delete_date_from_booking.rb, db/migrate/20230316141757_add_startand_end_date_bookings.rb, db/schema.rb
Changes in schema
migration files to delete and add new column
changes in booking new
=> added start and end date

app/assets/stylesheets/components/_map.scss, app/views/cars/index.html.erb
placed text center
placed map center
=> center changes

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/pages/_show_car.scss, app/views/bookings/index.html.erb, app/views/cars/show.html.erb
Spaced out the buttons at the bottom of the show page
=> spaced out buttons
